version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: "-"
    labels:
      - dependencies
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
    labels:
      - dependencies
    groups:
      all:
        patterns:
          - "*"
